all: graycode squares sequence_abandon words arr sequence
	true
graycode: graycode.c
	gcc -Wall -g graycode.c -o graycode
squares: squares.c
	gcc -Wall -g squares.c -o squares
sequence_abandon: sequence_abandon.c
	gcc -Wall -g sequence_abandon.c -o sequence_abandon
words: words.c
	gcc -Wall -g words.c -o words
arr: arr.c
	gcc -Wall -g arr.c -o arr 
sequence: sequence.c
	gcc -Wall -g sequence.c -o sequence
