all : Decompose Nickle Real Invertsub prz
	true
Decompose: decompose.c
	gcc -g -Wall decompose.c -o Decompose
Nickle: nickle.c
	gcc -g -Wall nickle.c -o Nickle 
Real: real.c
	gcc -g -Wall real.c -o Real
Invertsub: invertsub.c
	gcc -g -Wall invertsub.c -o Invertsub
prz: prz.c
	gcc -g -Wall prz.c -o prz

