all : rotate poisson cow nprime outstack
	true
rotate: rotate.c
	gcc -g -Wall rotate.c -o rotate
poisson: poisson.c
	gcc -g -Wall poisson.c -o poisson -lm
cow: cow.c
	gcc -g -Wall cow.c -o cow
nprime: nprime.c
	gcc -g -Wall nprime.c -o nprime 
outstack: outstack.c
	gcc -g -Wall outstack.c -o outstack
